services:
  backend:
    image: yourdockerhubusername/cms-backend:latest
    ports:
      - "5000:5000"

  frontend:
    image: yourdockerhubusername/cms-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
